### ISSUE TITLE
It works really well on iOS. Do you accept donation?

### ISSUE THREAD

**Issue by duyluandethuong** [gitn00b1337/expo-widgets#1]
After days of testing several tutorials, your repo is the simplest and it works for me. Need a clearer explanation in the Readme, I will create a PR for you in the next few days. Btw, do you accept donation? Want to send you a few thanks!

Also, looking forward for the Android widget compatibility

**Comment by gitn00b1337** [comment]
Hi, thanks a lot for the offer and kind words! I'd certainly accept a donation, thanks a lot. I've sent a request to GitHub for their sponsors option which should be approved the next few days or I can DM you my PayPal.

Yeah, the readme definitely needs an update, cheers. iOS plugin has been working in production without issues for me. I've got android working in the example project too, but I've just gone on holiday so it's not been production tested yet - back in 3 weeks and then it'll be a priority as I need it too!

**Comment by duyluandethuong** [comment]
Looking forward for the GitHub donation options. Please let me know when it's approved. Really appreciate your work and hope to see the instructions for Android widget!

**Comment by gitn00b1337** [comment]
Will do, thanks again

**Comment by gitn00b1337** [comment]
Hi, just to let you know it’s now set up (I think). I’ll be back polishing the android side and readme on 19th and pop an update here when instructions are done. Thanks

**Comment by duyluandethuong** [comment]
Already sent a small donation to you. Keep up good work!
