### ISSUE TITLE
Use with additional targets 

### ISSUE THREAD

**Issue by noman-ahmad** [gitn00b1337/expo-widgets#15]
Hey, first off this is a great plugin! I have a use case that in addition to creating iOS and Android widgets, I also need to create iOS watch app and Android watch app. I know Android watch apps are technically sperate apps, but iOS ones need to be linked as a target from the main app similar to widgets. Is there possibility to support such a development workflow through this plugin?

**Comment by gitn00b1337** [comment]
I've never made either but if it's just another target then you should be able to do similar as I have here.
Basically this library just injects what's needed into the Xcode project file, along with copying the widget files you provide.
I would assume it's the same process for watch apps and any other Xcode target. It's a bit of a ball ache, but if you create a new project in Xcode, take a copy of the project file, then add the target and see what changes you'll be able to figure out what's needed.
If you get stuck I'll try to help

**Comment by gitn00b1337** [comment]
Closing as no further update, hope it all goes well
