### ISSUE TITLE
Can't make it work on iPhone

### ISSUE THREAD

**Issue by sercanov** [gitn00b1337/expo-widgets#21]
Using version 2.0.0 with expo 51.0.17. It works great on simulator but Widget doesn't show up on real device. Extension and app are sharing the same app group. Any ideas? 

```
[
          '@bittingz/expo-widgets',
          {
            ios: {
              src: './widget/ios',
              devTeamId: 'NH54L24W4K',
              mode: 'development',
              moduleDependencies: ['MyData.swift', 'LogHandler.swift'],
              useLiveActivities: false,
              frequentUpdates: false,
              entitlements: {
                'com.apple.security.application-groups': [
                  'group.com.tickrcountdown.app.expowidgets'
                ]
              }
            },
            android: {
              src: './widget/android',
              widgets: [
                {
                  name: 'MyWidgetProvider',
                  resourceName: '@xml/my_widget_info'
                }
              ],
              distPlaceholder: 'optional.placeholder'
            }
          }
        ],
```

**Comment by gitn00b1337** [comment]
Does your widget do anything, aka network requests etc? The reason I ask is if anything crashes on widget preview, or if the app doesn't have the right permissions, the widgets just disappear without any feedback on device.

**Comment by sercanov** [comment]
No it just reads data from UserDefaults and display text. It's a date countdown app. Any way to debug?

**Comment by gitn00b1337** [comment]
What device & iOS version

**Comment by sercanov** [comment]
iPhone 12 Pro 
iOS 17.5.1

Nothing in console about widget too
<img width="534" alt="image" src="https://github.com/gitn00b1337/expo-widgets/assets/10291644/005c0288-73c2-44d5-99ac-b3fb67f2d781">

**Comment by gitn00b1337** [comment]
Was there any warning in eas build hidden away? Do you have other widgets on the phone? Have you tried restarting the phone? I've noticed quite a few articles on ios17 having issues with widgets but I don't expect it's that. Worth checking though.

I will look into adding more logging back into the library in the coming days when I get a chance which might help you pin it down.

**Comment by gitn00b1337** [comment]
I'd also recommend checking if the widget works on another device or not

**Comment by sercanov** [comment]
Weirdly, after the night it started to appear with a warning of "Please adopt containerBackground API". I didn't do anything new. I guess it's the iOS

**Comment by gitn00b1337** [comment]
Ok this looks like a widget ui issue not a library issue - please let me know if I can close this issue

https://stackoverflow.com/questions/76595240/widget-on-ios-17-beta-device-adopt-containerbackground-api

**Comment by sercanov** [comment]
Yeah it was resolved after migrating to container background api. thanks
