### ISSUE TITLE
CommandError: Cannot find module './plugin/build'

### ISSUE THREAD

**Issue by zheorekhy** [gitn00b1337/expo-widgets#25]
Hi. I'm trying to run the example by running:

`npm start `
or 
`npm prebuild:android`

within example folder. And I get such error:

% npm run prebuild:android

> expo-widgets-example@1.0.0 prebuild:android
> EXPO_NO_CACHE=true EXPO_NO_GIT_STATUS=true expo prebuild -p android --clean

Git status is dirty but the command will continue because EXPO_NO_GIT_STATUS is enabled...
(node:70517) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Cleared android code

CommandError: Cannot find module './plugin/build'
Require stack:
- /Users/eugene/Documents/Projects/expo-widgets/app.plugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config/build/Config.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config/build/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/prebuild/ensureConfigAsync.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/prebuild/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/bin/cli
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/expo/bin/cli

eugene@MacBook-Pro-Eugene example % 
eugene@MacBook-Pro-Eugene example % 
eugene@MacBook-Pro-Eugene example % 
eugene@MacBook-Pro-Eugene example % npm start

> expo-widgets-example@1.0.0 start
> expo start --dev-client

(node:70704) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Cannot find module './plugin/build'
Require stack:
- /Users/eugene/Documents/Projects/expo-widgets/app.plugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/prebuild/clearNativeFolder.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/utils/scheme.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/start/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/bin/cli
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/expo/bin/cli
Error: Cannot find module './plugin/build'
Require stack:
- /Users/eugene/Documents/Projects/expo-widgets/app.plugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/config-plugins/build/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/prebuild/clearNativeFolder.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/utils/scheme.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/src/start/index.js
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/@expo/cli/build/bin/cli
- /Users/eugene/Documents/Projects/expo-widgets/example/node_modules/expo/bin/cli
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/eugene/Documents/Projects/expo-widgets/app.plugin.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)

**Comment by gitn00b1337** [comment]
Update the npm package to latest

**Comment by zheorekhy** [comment]
@gitn00b1337 It's isn't a reason. I've found a solution. Before run the example we need to build the module from root `npm run build` and only then run the example!)
