### ISSUE TITLE
xcode override options

### ISSUE THREAD

**Issue by zheorekhy** [gitn00b1337/expo-widgets#26]
Where Can I specify this? https://github.com/gitn00b1337/expo-widgets?tab=readme-ov-file#overriding-xcode-options
xcode: {
    configOverrides: {
        SWIFT_VERSION: '5.0',
    },                        
},

I've got such error:

Updating podfile
⠹ Running prebuildAdding entitlement group.com.app.glucosense.expowidgets to config
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to determine Swift version for the following pods:

- `terra-react` is integrated by multiple targets that use a different Swift version: `GlucoSenseIncWidgetExtension` (Swift 5.4) and `GlucoSenseInc` (Swift 5.0).

pod install --repo-update --ansi exited with non-zero code: 1

**Comment by zheorekhy** [comment]
I've used the config in same way

```
[
        "@bittingz/expo-widgets",
        {
          "ios": {
            "src": "./widget/ios",
            "devTeamId": "C9853PNBF7",
            "mode": "production",
            "moduleDependencies": [],
            "useLiveActivities": false,
            "frequentUpdates": false,
            "entitlements": {
              "any xcode entitlement the widget needs": "entitlement value"
            },
            "xcode": {
              "configOverrides": {
                "SWIFT_VERSION": "5.4"
              }
            }
          }
        }
      ]
```

But I get same error:

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to determine Swift version for the following pods:

- `terra-react` is integrated by multiple targets that use a different Swift version: `GlucoSenseIncWidgetExtension` (Swift 5.4) and `GlucoSenseInc` (Swift 5.0).

**Comment by zheorekhy** [comment]
It's strange. I've removed terra plugin and had success with prebuild command. I've restored terra and still has success with prebuild.

**Comment by gitn00b1337** [comment]
Your main project is swift 5 and you're changing the widget project to 5.4, which causes that error. They have to be the same so I would advise changing the config to swift 5.0

**Comment by gitn00b1337** [comment]
Also, prebuild after changing config or you won't get the updated iOS project. Use --clean to avoid problems

**Comment by zheorekhy** [comment]
Yes I have now such config:

`[
        "@bittingz/expo-widgets",
        {
          "ios": {
            "src": "./widget/ios",
            "devTeamId": "C9853PNBF7",
            "mode": "production",
            "moduleDependencies": [],
            "useLiveActivities": false,
            "frequentUpdates": false,
            "entitlements": {
              "any xcode entitlement the widget needs": "entitlement value"
            },
            "xcode": {
              "configOverrides": {
                "SWIFT_VERSION": "5.0"
              }
            }
          }
        }
      ]`
      
      Thank you very much.
