### ISSUE TITLE
Error: Cannot find native module 'ExpoWidgets', js engine: hermes

### ISSUE THREAD

**Issue by zheorekhy** [gitn00b1337/expo-widgets#28]
App is crashed when I run it as usual (`expo start -c`) if I import `import * as ExpoWidgetsModule from '@bittingz/expo-widgets'.` How to handle it?

**Comment by gitn00b1337** [comment]
Npx expo doctor 

If no help, do a fresh development build and clean run

Aka https://docs.expo.dev/develop/development-builds/create-a-build/

Then

https://docs.expo.dev/develop/development-builds/use-development-builds/

**Comment by zheorekhy** [comment]
I use standard build expo-go.

**Comment by gitn00b1337** [comment]
You'll still need a development build as it uses native code, as per docs

**Comment by zheorekhy** [comment]
I see. I'v found such way:

```
async function sendWidgetData () {
    if (Constants.appOwnership !== 'expo') {
      const ExpoWidgetsModule = await import('@bittingz/expo-widgets')
      const json = JSON.stringify({ message: 'Hello from app!' })
      ExpoWidgetsModule.setWidgetData(json)
    } else {
      console.log('ExpoWidgetsModule initialization skipped in Expo Go')
    }
  }
```
