### ISSUE TITLE
[Question]. It's possible to develop a lock screen widget with this?

### ISSUE THREAD

**Issue by st4l1nR** [gitn00b1337/expo-widgets#3]
I succesfully made a home widget with this plugin but it is possible to make a lock screen widget with this plugin?

**Comment by gitn00b1337** [comment]
Hi, yes you can for iOS 100%. Just add the needed swift code. Android needs testing but my laptop was stolen so I'm stuck until January, but again it should just need the relevant kotlin code adding.

**Comment by gitn00b1337** [comment]
If you still need anything on this let me know. Closed due to inactivity
