### ISSUE TITLE
Exit Code 65 Using EAS to Build iOS

### ISSUE THREAD

**Issue by nbonatsakis** [gitn00b1337/expo-widgets#30]
Environment:
- EAS/Expo 51
- Xcode 15
- iOS 17

Issue:

I am trying to build my Expo app using npx eas build. Prior to adding this lib, build was successful. However, now, I can't et past an Archive Error Exit Code 65 when EAS is running fastlane. 

If I run npx expo prebuild -p ios and open the build in Xcode, I can successfully archive using Automatic signing on both app and widget targets. 

So I'm stuck. It seems like the Exit Code 65 has something to do with signing, but it's strange that Xcode can archive with no problem. 

Please let me know if there's anything else I can provide for helping resolve this.

**Comment by gitn00b1337** [comment]
I'd go through the readme steps and double check everything is correct, especially the bundle ids matching.

If still an issue, then send me your plugin config, module file, and the eas full logs.
