### ISSUE TITLE
- `EXAV` is integrated by multiple targets that use a different Swift version:

### ISSUE THREAD

**Issue by st4l1nR** [gitn00b1337/expo-widgets#6]
So i made my widget in swfit 5.0 but on build it raise this error ```- `EXAV` is integrated by multiple targets that use a different Swift version: `flowwyWidgetExtension` (Swift 5.4) and `flowwy` (Swift 5.0).``` , when i run it local i modified the podfile to change 5.4 (widget version) to 5.0 and the build went well , the problem it's when i try to upload to eas since the process it's automatic and this can't be changed during the process. It's widget automaticallly building in 5.4 version?

### More specifications
Expo version 49.0.21
Expo widgets version 0.5.53

**Comment by gitn00b1337** [comment]
Hi,

Sounds like eas is forcing a mismatch of swift version. Try adding the following to your app config:

```
[
                "@bittingz/expo-widgets",
                {
                    ios: {
                        ...
                        xcode: {
                            configOverrides: {
                                SWIFT_VERSION: '5.0',
                            },                        
                        },
                    },              
                }
            ],
```

**Comment by st4l1nR** [comment]
It worked thanks!
